### ISSUE TITLE
Linux 5.x

### ISSUE THREAD

**Issue by ps-chong** [GOOD-Stuff/AXI-DMA-API#2]
Hi,

Is this API tested on the linux kernel 5.x version?

Thanks.

**Comment by GOOD-Stuff** [comment]
Hi @eric950722 ! 
Unfortunately I don't have a Zynq board for testing at the moment, so I can't guarantee that this API will work with the 5.x kernel.

**Comment by GOOD-Stuff** [comment]
If you can check this, please let me know!
